#!/bin/bash

echo "🔍 DIAGNOSTIC ERROR 502 - Railway Application"
echo "============================================="

echo "📊 ANALYSE DE L'ERREUR 502:"
echo "   HTTP Status: 502 Bad Gateway"
echo "   Host: mage-noir-deckbuilder.up.railway.app"
echo "   Path demandé: /"
echo "   Durée: 139ms"
echo ""

echo "🔍 SIGNIFICATION ERROR 502:"
echo "   ✅ Railway proxy fonctionne"
echo "   ✅ URL accessible depuis internet"
echo "   ❌ Application Spring Boot ne répond pas sur port 8080"
echo "   ❌ Soit: crash au démarrage, soit: mauvaise configuration"
echo ""

echo "🎯 PROBLÈME PROBABLE - CONTEXT PATH:"
echo "   Configuration: server.servlet.context-path: /api"
echo "   URL testée: https://mage-noir-deckbuilder.up.railway.app/"
echo "   URL correcte: https://mage-noir-deckbuilder.up.railway.app/api/"
echo ""

echo "✅ URLS À TESTER:"
echo "   Health check:"
echo "   curl https://mage-noir-deckbuilder.up.railway.app/api/actuator/health"
echo ""
echo "   API Cards:"
echo "   curl https://mage-noir-deckbuilder.up.railway.app/api/cards"
echo ""
echo "   Swagger UI:"
echo "   https://mage-noir-deckbuilder.up.railway.app/api/swagger-ui.html"
echo ""

echo "🔧 VÉRIFICATIONS RAILWAY:"
echo "   1. Logs Railway (voir si l'app démarre):"
echo "      railway logs --deployment"
echo ""
echo "   2. Variables d'environnement:"
echo "      - DATABASE_URL présente ?"
echo "      - SPRING_PROFILES_ACTIVE=prod ?"
echo "      - JWT_SECRET configuré ?"
echo ""

echo "⚡ SOLUTIONS POSSIBLES:"
echo "   A. Si l'app démarre mais context-path:"
echo "      → Tester /api/actuator/health"
echo ""
echo "   B. Si l'app crash au démarrage:"
echo "      → Vérifier logs Railway"
echo "      → Problème probable: JWT_SECRET manquant"
echo ""
echo "   C. Si problème de port:"
echo "      → Railway détecte automatiquement port 8080"
echo "      → Vérifier server.port configuration"
echo ""

echo "🎯 PROCHAINE ÉTAPE:"
echo "   Tester: curl https://mage-noir-deckbuilder.up.railway.app/api/actuator/health"
