#!/bin/bash

echo "🔧 DIAGNOSTIC RAILWAY PORT CONFIGURATION"
echo "========================================"

echo "📊 CONFIGURATION ACTUELLE:"
echo "   ✅ Application démarre sur port 8080 ✓"
echo "   ✅ Context path: /api ✓"
echo "   ✅ Logs montrent: 'Tomcat started on port 8080 (http) with context path /api'"
echo ""

echo "🔍 PROBLÈME 502 POSSIBLE:"
echo "   1. Railway n'a pas encore détecté le port 8080"
echo "   2. Railway routing pas encore configuré"
echo "   3. Problème temporaire de proxy Railway"
echo ""

echo "⚙️ VÉRIFICATIONS RAILWAY DASHBOARD:"
echo "   1. Aller dans Railway Dashboard"
echo "   2. Votre service → Settings → Networking"
echo "   3. Vérifier 'Public Port' = Auto-detected ou 8080"
echo "   4. Vérifier 'Custom Domain' configuré correctement"
echo ""

echo "🚀 SOLUTIONS:"
echo "   A. ATTENDRE 2-3 MINUTES (Railway routing prend du temps)"
echo "   B. REDÉMARRER LE SERVICE:"
echo "      Railway Dashboard → Deploy → Restart"
echo ""
echo "   C. FORCER LA DÉTECTION DU PORT:"
echo "      Railway Dashboard → Settings → Variables"
echo "      Ajouter: PORT=8080"
echo ""
echo "   D. VÉRIFIER CUSTOM DOMAIN:"
echo "      Dashboard → Networking → Regenerate Domain"
echo ""

echo "🧪 TESTS À EFFECTUER (dans 2-3 min):"
echo "   curl -v https://mage-noir-deckbuilder.up.railway.app/api/actuator/health"
echo "   (Le -v montre les détails de connexion)"
echo ""

echo "💡 NOTES IMPORTANTES:"
echo "   - Railway détecte automatiquement le port 8080"
echo "   - Pas besoin de spécifier le port dans l'URL"
echo "   - URL correcte: https://mage-noir-deckbuilder.up.railway.app/api/"
echo "   - Le problème 502 est souvent temporaire après déploiement"
