spring.application.name=generic.deck.builder

# ================================
# ? Connexion PostgreSQL
# ================================
spring.datasource.url=jdbc:postgresql://localhost:5432/generic_deck_builder
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# ? JPA / Hibernate
# ================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ================================
# ? Encodage
# ================================
spring.datasource.hikari.connection-init-sql=SET NAMES 'UTF8'
server.servlet.encoding.charset=UTF-8

spring.profiles.active=dev

jwt.secret=myUltraSecureJwtSecretKey!123456

